blank_issues_enabled: true
contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/nostromos/contribute
    about: Please read through before making contributions.
  - name: ğŸˆâ€â¬› Mike's Personal Site
    url: https://what.lol
    about: Check out my personal site to learn more about me.
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://antfu.me/posts/why-reproductions-are-required
    about: Reproductions are very important to help maintainers understand and fix your issues.
